---
# Ansible playbook to run Windows Update and restart, if required
#
# http://docs.ansible.com/ansible/win_updates_module.html
# https://docs.ansible.com/ansible/win_reboot_module.html
- hosts: all
  tasks:
    - name: Download catalog from specified URL
      win_get_url:
        url: "{{catalog_path}}/{{catalog_name}}.hzp"
        dest: c:\DatabaseBkup\
        url_username: "{{username}}"
        url_password: "{{password}}"
    - name: Download ActivateCatalog zip
      win_get_url:
        url: "https://github.com/IAMShashankk/AWX_CatalogActive/archive/master.zip"
        dest: c:\temp\
    - name: Unzip the Download ActivateCatalog zip
      win_unzip:
        src: c:\temp\master.zip
        dest: C:\temp\
        rm: True
      when: file_info.stat.exists==false
